# Feature-Selection

**Retrival theimportant features , selrcting an important features is very important step before going to ML**

- Dropping the constant features (Regression and classification)

- Information gain(Classification)

- p-value(Regression)

- VIF(Regression)

- Forward selection and backward selection (Regression and classification)

- coorelation with target column(Regression and classification)


## Feature selection methods 

### 1) Variance Threshold :
    
    - based on variance we can decide the data is constant or varying 
    
    - data is not varing much means , data has unique values 
    
    - foe ex, we have seen in loan prediction dataset  , loan term:360
        
    - python by default will use variance =0 , it will drop those features which are having variance=0
    
    - variance threshold is hyper parameter , we can keep threshold as any value 
    
    - based on internal team discussion 
    
    - we will drop those features which are having <= threshold value 
    
    
### 2) P-value :
    
    - H0 : there is no relation x and y
        
    - H1 : there is  relation x and y
        
    - p<0.5:
          
        - raject the null hypothesis : **which means do not include the variables**
        
    p>0.5:
        
        - not reject the null hypothesis : **which means include the variables**
            
            
### 3) Mutual info classify:
        
        - KNN and entropy
        
        - it will give the relation between input and output will pick which are having more relation
        
        - input vs output
        
            - 1) Entropy
            
            - 2) KNN
            
            - 3) R-square: explainability about y based on x
                
                
### 4) Forward selection and backward selection :
       
    
    
    
    **Forward selection method**
         
        - start with empty set of features 
            
        - iterate through each features and select the one features that improves model performance 
        
        - continue adding features one by one till we meet our creteria 
        
    **Backward selection method**
        
        - start with full set of features 
        
        - iterate through each features by removing the features which is having less impact on the model
        
        - continue the process , till your performance is stable 
        
- Both Forward selection and backward selection methods are complex in nature 

- More time taken , will avoid in general 


### 5) Variance inflation factor (VIF):
           
    - VIF will give the analysis of multicollinearity
    
    - In VIF will find the R-sq value of each input features wrt other input features
    
    - will keep one features as input and other features are consider as output in regression equation 
    
    - This will keep on iterate through all features 
    
    - every feature behave as input as well as output
    
    - As we know every Regression line give Rsquare value from that value will find VIF
    
    - will drop the features which are having VIF>5 or VIF>10 based on internal team discussion
    




# method 1) Variance Threshold

In [3]:
import pandas as pd

In [4]:
dict1 = {'A': [100,200,300,400],
        'B': [1,2,3,4],
        'C': [10,20,30,40],
        'D': [10,10,10,10]}

df=pd.DataFrame(dict1)
df

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [5]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
vt.fit(df)

VarianceThreshold(threshold=0)

In [6]:
dir(vt)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'feature_names_in_',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_support',
 'inve

In [7]:
vt.variances_
# 300 is the first column variance (true)
# 1.25 is second column variance (true)
# 30 is column variance(true)
# 0 is fourth column variance (false)

array([300.  ,   1.25,  30.  ,   0.  ])

In [8]:
vt.get_support()

array([ True,  True,  True, False])

In [9]:
vt.get_params()
# Hyper parameter that we are providing in the pacakage or inside the function 

{'threshold': 0}

In [10]:
vt.threshold

0

In [11]:
cols = vt.get_feature_names_out()
# these features only we want to include 
df[cols]

A  B   C
0  100  1  10
1  200  2  20
2  300  3  30
3  400  4  40

In [12]:
#v apply on wine dataset

In [20]:
df=pd.read_csv("C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv")
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
### Make  sure before fitting the datafraeme , do not include output column

X=df.drop('quality',axis=1)
X.dropna(inplace=True)
X.reset_index(inplace=True)
X.drop('index',axis = 1,inplace=True)
# x is self a data frame

vt.fit(X)
vt.variances_

array([3.02952057e+00, 3.20423261e-02, 3.79237511e-02, 1.98665392e+00,
       2.21375732e-03, 7.10000000e+01, 2.83000000e+02, 3.55980179e-06,
       2.38202742e-02, 2.87146470e-02, 1.13493717e+00])

In [21]:
vt.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [22]:
vt.get_params()

{'threshold': 0}

In [23]:
vt.threshold

0

In [24]:
cols = vt.get_feature_names_out()
X[cols]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

# method 2) Imformation gain

## mutual into classify
   

In [25]:
# read the data 
data=pd.read_csv("C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv")

data.dropna(inplace=True)
data.reset_index(inplace=True)
data.drop('index',axis = 1,inplace=True)
# seperate input and target features 
    


In [26]:
X=data.drop('quality',axis=1) 
y=data['quality']

In [27]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [28]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [29]:
from sklearn.feature_selection import mutual_info_classif
MI=mutual_info_classif(X,y)
MI

array([0.0562903 , 0.11629205, 0.07062349, 0.03278245, 0.02440274,
       0.0283234 , 0.09184094, 0.08222267, 0.01285058, 0.11284507,
       0.16688631])

In [30]:
import numpy as np
np.sum(MI)

0.7953600019156257

In [31]:
len(MI)

11

In [32]:
d=pd.DataFrame(MI,
            columns=['Information gain'],
            index=X.columns)
d.sort_values('Information gain',ascending=False)

# wee need to select manuanuly
# how about python will provide top 5 or top 10

Information gain
alcohol                       0.166886
volatile acidity              0.116292
sulphates                     0.112845
total sulfur dioxide          0.091841
density                       0.082223
citric acid                   0.070623
fixed acidity                 0.056290
residual sugar                0.032782
free sulfur dioxide           0.028323
chlorides                     0.024403
pH                            0.012851

### selectKBest 

In [33]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif
import pandas as pd 

# read the data 
data=pd.read_csv("C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv")
data.dropna(inplace=True)
data.reset_index(inplace=True)
data.drop('index',axis = 1,inplace=True)

# seperate input and output 
x=data.drop('quality',axis=1)
y=data['quality']

In [34]:
# assume that u did not mutual_info_classif

top_5=SelectKBest(mutual_info_classif,k=5)
val=top_5.fit(X,y)
val

SelectKBest(k=5,
            score_func=<function mutual_info_classif at 0x000001CE6B6922A0>)

In [35]:
val.get_params()

{'k': 5,
 'score_func': <function sklearn.feature_selection._mutual_info.mutual_info_classif(X, y, *, discrete_features='auto', n_neighbors=3, copy=True, random_state=None)>}

In [36]:
val.get_support()

array([False,  True, False, False, False, False,  True,  True, False,
        True,  True])

In [37]:
val.get_feature_names_out()

array(['volatile acidity', 'total sulfur dioxide', 'density', 'sulphates',
       'alcohol'], dtype=object)

In [38]:
dir(val)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_params',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'feature_names_in_',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'ge