# step-1:  import package

In [1]:

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# step-2 : read the data

In [2]:
df1="C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv"
vine_df=pd.read_csv(df1)
vine_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               NaN               NaN          NaN             NaN        NaN   
1               7.4             0.700         0.00             1.9      0.076   
2               NaN               NaN          NaN             NaN        NaN   
3               7.8             0.880         0.00             2.6      0.098   
4               NaN               NaN          NaN             NaN        NaN   
...             ...               ...          ...             ...        ...   
3193            6.3             0.510         0.13             2.3      0.076   
3194            NaN               NaN          NaN             NaN        NaN   
3195            5.9             0.645         0.12             2.0      0.075   
3196            NaN               NaN          NaN             NaN        NaN   
3197            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     NaN                   NaN      NaN   NaN        NaN   
1                    11.0                  34.0  0.99780  3.51       0.56   
2                     NaN                   NaN      NaN   NaN        NaN   
3                    25.0                  67.0  0.99680  3.20       0.68   
4                     NaN                   NaN      NaN   NaN        NaN   
...                   ...                   ...      ...   ...        ...   
3193                 29.0                  40.0  0.99574  3.42       0.75   
3194                  NaN                   NaN      NaN   NaN        NaN   
3195                 32.0                  44.0  0.99547  3.57       0.71   
3196                  NaN                   NaN      NaN   NaN        NaN   
3197                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         NaN      NaN  
1         9.4      5.0  
2         NaN      NaN  
3         9.8      5.0  
4         NaN      NaN  
...       ...      ...  
3193     11.0      6.0  
3194      NaN      NaN  
3195     10.2      5.0  
3196      NaN      NaN  
3197     11.0      6.0  

[3198 rows x 12 columns]

In [3]:
vine_df.shape

(3198, 12)

In [4]:
vine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
vine_df.dropna(inplace=True)


In [6]:
vine_df.reset_index(inplace=True)

In [7]:
vine_df.drop('index',axis = 1,inplace=True)

In [8]:
vine_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4      5.0  
1      9.8      5.0  
2      9.8      5.0  
3      9.8      6.0  
4      9.4      5.0

In [9]:
vine_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4      5.0  
1      9.8      5.0  
2      9.8      5.0  
3      9.8      6.0  
4      9.4      5.0

In [10]:
vine_df.shape

(1599, 12)

In [11]:
vine_df.shape

(1599, 12)

In [12]:
vine_df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [13]:
vine_df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                 float64
dtype: object

- we divide data into two parts into input and output data 
- input data = x : output data = y.
- again we divide data into two parts i.e train and test
- input data
  - input train data = x_train : output test data : x_test
- output data
  - output train data = y_train : output test data : y_test
- model developement happens on train data i.e. x_train and y_train
- model will predict by passing x_text these are called y_prediction
- y_prediction will comp with y_test these is called accuracy/test error

# step-3 : divide into x and y

In [14]:
X=vine_df.drop('quality',axis=1)
y=vine_df['quality']

# step-4 : divide into train and test

- will use train test split from sklearn model selectin
- It will take following parameter
   - X:input data
   - y:output data
   - test size = 0.3 , 30% test data , 70% train data 
   - by default 75:25
   - random state 
        - we want select obs randomly 
        - many possible combinations 
        - every possible combination represent as a number
        - 1,2,3,4,5,6,7,8,9,10
        - select 5 number ramdomly : how many combination 
        - random state = 42
        - random state = 1234

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,   # input data
                                               y,   # output data
                                               random_state=1234, # it select 
                                               test_size=0.30)
                                            

In [16]:
#vine_df.shape  
#x:11  , y:1
#1599 = 100%
#? = 30%

#1599*30/100

#test data has 480
#train data has 1599-480=1119

#vine_df  : 12 columns 1599 rows (1599,12)
#X_train  : 11 columns 1119 rows (1119,11)
# etc for ........

**Check point - 1**

 - check the shape

In [17]:
X_train.shape , X_test.shape

((1119, 11), (480, 11))

In [18]:
y_train.shape , y_test.shape

((1119,), (480,))

In [19]:
print("the shape of data frame is :",vine_df.shape)
print("the shape of X_train is :",X_train.shape)
print("the shape of X_test is :",X_test.shape)
print("the shape of y_train is :",y_train.shape)
print("the shape of y_test is :",y_test.shape)

the shape of data frame is : (1599, 12)
the shape of X_train is : (1119, 11)
the shape of X_test is : (480, 11)
the shape of y_train is : (1119,)
the shape of y_test is : (480,)


**Check point-2**:

    - check the obs indexes of X_train and y_train both should match
    
    - lly X_test and y_test both should match

In [20]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
642             9.9             0.540         0.45             2.3      0.071   
678             8.3             0.780         0.10             2.6      0.081   
412             7.1             0.735         0.16             1.9      0.100   
73              8.3             0.675         0.26             2.1      0.084   
985             7.4             0.580         0.00             2.0      0.064   
...             ...               ...          ...             ...        ...   
1228            5.1             0.420         0.00             1.8      0.044   
1077            8.6             0.370         0.65             6.4      0.080   
1318            7.5             0.630         0.27             2.0      0.083   
723             7.1             0.310         0.30             2.2      0.053   
815            10.8             0.450         0.33             2.5      0.099   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
642                  16.0                  40.0  0.99910  3.39       0.62   
678                  45.0                  87.0  0.99830  3.48       0.53   
412                  15.0                  77.0  0.99660  3.27       0.64   
73                   11.0                  43.0  0.99760  3.31       0.53   
985                   7.0                  11.0  0.99562  3.45       0.58   
...                   ...                   ...      ...   ...        ...   
1228                 18.0                  88.0  0.99157  3.68       0.73   
1077                  3.0                   8.0  0.99817  3.27       0.58   
1318                 17.0                  91.0  0.99616  3.26       0.58   
723                  36.0                 127.0  0.99650  2.94       1.62   
815                  20.0                  38.0  0.99818  3.24       0.71   

      alcohol  
642       9.4  
678      10.0  
412       9.3  
73        9.2  
985      11.3  
...       ...  
1228     13.6  
1077     11.0  
1318      9.8  
723       9.5  
815      10.8  

[1119 rows x 11 columns]

In [21]:
y_train

642     5.0
678     5.0
412     5.0
73      4.0
985     6.0
       ... 
1228    7.0
1077    5.0
1318    6.0
723     5.0
815     5.0
Name: quality, Length: 1119, dtype: float64

In [22]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  
688       9.4  
961       9.3  
726      11.1  
537      10.7  
1544     11.2  
...       ...  
1461     10.0  
1591     11.6  
1045     11.4  
1498     10.8  
42       10.5  

[480 rows x 11 columns]

In [23]:
y_test

688     5.0
961     5.0
726     6.0
537     6.0
1544    7.0
       ... 
1461    4.0
1591    6.0
1045    6.0
1498    6.0
42      6.0
Name: quality, Length: 480, dtype: float64

In [24]:
#step-1: import package
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# step-2 :
df1="C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv"
vine_df=pd.read_csv(df1)
vine_df

# step-3:
vine_df.dropna(inplace=True)
vine_df.reset_index(inplace=True)
vine_df.drop('index',axis = 1,inplace=True)

In [25]:
vine_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4      5.0  
1      9.8      5.0  
2      9.8      5.0  
3      9.8      6.0  
4      9.4      5.0

In [26]:
vine_df.shape

(1599, 12)

In [27]:
#step-1: import package
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# step-2 :
df1="C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv"
vine_df=pd.read_csv(df1)
vine_df

# step-:
vine_df.dropna(inplace=True)
vine_df.reset_index(inplace=True)
vine_df.drop('index',axis = 1,inplace=True)

# step-3 :
X=vine_df.drop('quality',axis=1)
y=vine_df['quality']

# step 4 :
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,   # input data
                                               y,   # output data
                                               random_state=1234, # it select 
                                               test_size=0.30)
                                            
    
X_train.shape , X_test.shape
y_train.shape , y_test.shape

((1119,), (480,))

In [28]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
642             9.9             0.540         0.45             2.3      0.071   
678             8.3             0.780         0.10             2.6      0.081   
412             7.1             0.735         0.16             1.9      0.100   
73              8.3             0.675         0.26             2.1      0.084   
985             7.4             0.580         0.00             2.0      0.064   
...             ...               ...          ...             ...        ...   
1228            5.1             0.420         0.00             1.8      0.044   
1077            8.6             0.370         0.65             6.4      0.080   
1318            7.5             0.630         0.27             2.0      0.083   
723             7.1             0.310         0.30             2.2      0.053   
815            10.8             0.450         0.33             2.5      0.099   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
642                  16.0                  40.0  0.99910  3.39       0.62   
678                  45.0                  87.0  0.99830  3.48       0.53   
412                  15.0                  77.0  0.99660  3.27       0.64   
73                   11.0                  43.0  0.99760  3.31       0.53   
985                   7.0                  11.0  0.99562  3.45       0.58   
...                   ...                   ...      ...   ...        ...   
1228                 18.0                  88.0  0.99157  3.68       0.73   
1077                  3.0                   8.0  0.99817  3.27       0.58   
1318                 17.0                  91.0  0.99616  3.26       0.58   
723                  36.0                 127.0  0.99650  2.94       1.62   
815                  20.0                  38.0  0.99818  3.24       0.71   

      alcohol  
642       9.4  
678      10.0  
412       9.3  
73        9.2  
985      11.3  
...       ...  
1228     13.6  
1077     11.0  
1318      9.8  
723       9.5  
815      10.8  

[1119 rows x 11 columns]

In [29]:
y_train


642     5.0
678     5.0
412     5.0
73      4.0
985     6.0
       ... 
1228    7.0
1077    5.0
1318    6.0
723     5.0
815     5.0
Name: quality, Length: 1119, dtype: float64

In [30]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  
688       9.4  
961       9.3  
726      11.1  
537      10.7  
1544     11.2  
...       ...  
1461     10.0  
1591     11.6  
1045     11.4  
1498     10.8  
42       10.5  

[480 rows x 11 columns]

In [31]:
y_test

688     5.0
961     5.0
726     6.0
537     6.0
1544    7.0
       ... 
1461    4.0
1591    6.0
1045    6.0
1498    6.0
42      6.0
Name: quality, Length: 480, dtype: float64

# step-5 : Model developement

      - import the package 
      - save the package 
      - apply fit transform

In [32]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

# step-6: Model Predictions 

In [33]:
# model predictions hapens on X_test
y_predictions=LR.predict(X_test)

In [34]:
y_predictions

array([5.15272674, 5.32546327, 5.63662519, 5.51245819, 6.35588496,
       5.39028618, 5.37580837, 5.94379165, 5.49446987, 6.98211458,
       4.92847919, 5.18177228, 5.73271386, 5.56085417, 5.53985028,
       5.25272042, 4.93424659, 5.12423646, 6.27626835, 5.12589226,
       5.06691612, 5.91039778, 5.1797551 , 5.45854364, 5.72531378,
       6.31002431, 5.30913419, 5.50678991, 6.04808131, 5.47609822,
       4.72291628, 6.20818055, 5.21920961, 5.62421184, 5.55062526,
       5.52259916, 6.36735043, 5.23288886, 5.49938736, 5.80792898,
       5.16587916, 6.13318292, 5.72636822, 5.33537114, 5.63701918,
       4.96463531, 4.88029661, 5.78938553, 6.36333952, 5.56149953,
       4.95005899, 5.75085354, 6.67236186, 6.16951277, 5.34056761,
       5.12096361, 6.19641543, 5.21584694, 6.46449078, 5.25590493,
       5.27667097, 5.17871421, 5.09122333, 5.63083824, 5.01946398,
       6.16336001, 5.7427919 , 6.337122  , 5.28732968, 6.05063646,
       5.7342916 , 5.57340483, 5.21043842, 6.18633591, 5.50678

In [35]:
X_test.iloc[0]

fixed acidity           7.7000
volatile acidity        0.6600
citric acid             0.0400
residual sugar          1.6000
chlorides               0.0390
free sulfur dioxide     4.0000
total sulfur dioxide    9.0000
density                 0.9962
pH                      3.4000
sulphates               0.4700
alcohol                 9.4000
Name: 688, dtype: float64

In [36]:
X_test.iloc[0] # series
# in order to pass a test sample to a model
# we need to pass a list of values 
# or anarry as well as tuple of values 
X_test.iloc[0].values

array([7.7   , 0.66  , 0.04  , 1.6   , 0.039 , 4.    , 9.    , 0.9962,
       3.4   , 0.47  , 9.4   ])

In [37]:
type(X_test.iloc[0])

pandas.core.series.Series

In [38]:
LR.predict([X_test.iloc[0].values,X_test.iloc[1].values])

array([5.15272674, 5.32546327])

**batch predictions vs realtime predictions**

- After modal developement we pass a batch of input 
- In the above examples we are passing 480 obs/tuple at a time 
- This is called as Batch predictions 
- 

**Real time or Endpoint oredictimns**
   
   - After modal developement will pass a single obs
   - It will give quick response 
   - So that is called as realtime predictions 
   
**Note**
   - No of values we are passing in a list = number of collections 
   - On how many columns your modal trained , that many values modal consider 

In [39]:
#take some list of values 
LR.predict([[1,2,3,4,5,6,7,8,9,10,11]]) 
# X has 10 features, but LinearRegression is expecting 11 features as input i.e we have to pass 11 values 

array([-82.48338949])

In [40]:
X_test.shape,y_test.shape,y_predictions.shape

((480, 11), (480,), (480,))

In [41]:
test_data = X_test
test_data['y_actual']=y_test
test_data['y_predictions']=y_predictions
test_data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  y_actual  y_predictions  
688       9.4       5.0       5.152727  
961       9.3       5.0       5.325463  
726      11.1       6.0       5.636625  
537      10.7       6.0       5.512458  
1544     11.2       7.0       6.355885  
...       ...       ...            ...  
1461     10.0       4.0       5.163071  
1591     11.6       6.0       5.556391  
1045     11.4       6.0       6.167418  
1498     10.8       6.0       5.271424  
42       10.5       6.0       5.674091  

[480 rows x 13 columns]

In [42]:
y_test # y_test is a series 
y_predictions # y_predictons is numpy array values 

print(y_test.values[:5].astype('int'))
print(y_predictions[:5])

[5 5 6 6 7]
[5.15272674 5.32546327 5.63662519 5.51245819 6.35588496]


# Step-7 : Model evaluation

In [43]:
# RSME -----------not available
# MSE
# MAE
# R-squared

from sklearn.metrics import r2_score,mean_squared_error,accuracy_score

In [44]:
R2=r2_score(y_test,y_predictions)
MSE=mean_squared_error(y_test,y_predictions)
#MSE**(1/2)
RMSE=np.sqrt(MSE)
#accuracy_score(y_test,y_predictions) # it is a regression tech
print("R-sqaure:",R2)
print("MSE:",MSE)
print("RMSE:",RMSE)

R-sqaure: 0.31285862790752283
MSE: 0.3918584723116435
RMSE: 0.625986000092369


# MSE formula

- ### Step-1 : we already has y_actual (y_test) data and y_prediction  (model predictions)
- ### Step-2 : throungh a for loop will call each value and subtract both 
- ### Step-3 : square the subtractions and append in a list 
- ### Step-4 : get the sum of all the values in a list
- ### Step-5 : Divide by len(y_test) or len(y_predictions )

In [45]:
s=0
for i in range(len(y_test)):
    v1=y_test.values[i]-y_predictions[i]
    v2=v1**2
    s=s+v2
print(s/len(y_test))

0.3918584723116432


# calculate the dist between each point in v1 with v2
 
<img src="https://www.chilimath.com/wp-content/uploads/2018/12/the_distance_formula.png" jsaction="VQAsE" class="sFlh5c pT0Scc iPVvYb" style="max-width: 477px; height: 160px; margin: 0px; width: 350px;" alt="Distance Formula and Examples | ChiliMath" jsname="kn3ccd" aria-hidden="false">

In [46]:
# calculate the dist between each point in v1 with v2
 

v1 = [(1,2),(3,5),(5,7)]
v2 = (10, 20)

for point in v1:
    distance = ((point[0] - v2[0])**2 + (point[1] - v2[1])**2)**0.5
    print(f"Distance between {point} and {v2}: {distance}")


Distance between (1, 2) and (10, 20): 20.12461179749811
Distance between (3, 5) and (10, 20): 16.55294535724685
Distance between (5, 7) and (10, 20): 13.92838827718412


## feature selection is Regression problems
- p-values concept 
    - H-0 : there is no relation between independent variable and dependent variable 
    - H_a : There is a relation between independent variable and dependent variable
    - p>alpha : not reject the null (H_0) hypothesis

<img src="https://i.ytimg.com/vi/2pohFqtQkMk/maxresdefault.jpg" jsaction="VQAsE" class="sFlh5c pT0Scc iPVvYb" style="max-width: 1280px; height: 166px; margin: 0px; width: 295px;" alt="Hypothesis Test for Simple Linear Regession" jsname="kn3ccd" aria-hidden="false">

**Sklearn package will not give the p value**

**So for p-values we need to stats modal package**

**Inside stats model we have OLS method available**

In [48]:
LR.predict([[1,2,3,4,5,6,7,8,9,10,11]])

array([-82.48338949])

# step-10
### method - 1
 **Stasts.OLS method**

In [ ]:
from statsmodels.api import OLS
OLS(y_train,X_train).fit().summary()

- Based on aplpha = 0.5 
- we will reject 3 columns = fixed acidity , citric acid , residual sugar
- Again we need to build the model by using other features 

### method -2
**Correlation between features** 

In [ ]:
cols = ['fixed acidity' , 'citric acid' , 'residual sugar']
new_data=vine_df.drop(cols,axis=1)

In [ ]:
new_data


In [ ]:
corr = new_data.corr()

In [ ]:
plt.figure(figsize=(8,10))
sns.heatmap(corr , annot=True)

- From above corelation 
    - Total sulphur dioxide and free sulpur dioxide are highly positive correlated 
    - 0.67
    - we can remove any one of the column
 - Remove the column which is having less relation with target data

In [ ]:
new_data.columns

In [ ]:
new_data.columns
col1= new_data['free sulfur dioxide']
col2= new_data['total sulfur dioxide']
plt.scatter(col1,col2)

In [ ]:
new_data.columns
col1= new_data['alcohol']
col2= new_data['quality']
plt.scatter(col1,col2)

# Method - 3
### Variance threshhold methods

- some times columns value are not very much
- for example in Loan prediction data : we have a column loan term 360
- the data is not vary across, then we can remove those column
- every data has some variance available
- if the variance is zero means, the data is not varying
- the data has most of the time only one values is there
- it is available sklear.feature selection

# step 11: Save the model 

dont run step 10 i.e feature selection now

- once model developed we need to save the model

- that model can use by any one

- Model we can save in different formats 

    - pickle     .pkl
    
    - joblib     .joblib
    
    - save (in deep learning)
    
    
 - if u wnat to write pickle.dump
 - if u want to read pickle.load

In [49]:
import pickle
pickle.dump (LR,
            open ('linear_wine_model.pkl','wb'))

# Model name = LR
# In modal name is : linear_wine_model
# extension : .pkl
# wb : write in bytes 

# Step-12 : Load the model

In [50]:
model = pickle.load(open('linear_wine_model.pkl', 'rb'))
model

LinearRegression()

# Step 13 : Predictions 

In [55]:
model.predict([[1,2,3,4,5,6,7,8,9,10,11]])

array([-82.48338949])

In [56]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  y_actual  y_predictions  
688       9.4       5.0       5.152727  
961       9.3       5.0       5.325463  
726      11.1       6.0       5.636625  
537      10.7       6.0       5.512458  
1544     11.2       7.0       6.355885  
...       ...       ...            ...  
1461     10.0       4.0       5.163071  
1591     11.6       6.0       5.556391  
1045     11.4       6.0       6.167418  
1498     10.8       6.0       5.271424  
42       10.5       6.0       5.674091  

[480 rows x 13 columns]

In [61]:
#step-1: import package
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# step-2 :
df1="C:\\Users\\admin\\OneDrive\\PRATIK\\NARESH IT\\DATA SCIENCE\\DATA SETS\\csv\\winequality_red.csv"
vine_df=pd.read_csv(df1)
vine_df

# step-:3
vine_df.dropna(inplace=True)
vine_df.reset_index(inplace=True)
vine_df.drop('index',axis = 1,inplace=True)

# step- :4
X=vine_df.drop('quality',axis=1)
y=vine_df['quality']

# step 4  :
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,   # input data
                                               y,   # output data
                                               random_state=1234, # it select 
                                               test_size=0.30)

# step 6 : develope the model
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

# step 7 : save the model
import pickle
pickle.dump (LR,
            open ('linear_model.pkl','wb'))

# step 8 : load
model = pickle.load(open('linear_model.pkl', 'rb'))
model


LinearRegression()

In [62]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  
688       9.4  
961       9.3  
726      11.1  
537      10.7  
1544     11.2  
...       ...  
1461     10.0  
1591     11.6  
1045     11.4  
1498     10.8  
42       10.5  

[480 rows x 11 columns]

In [63]:
model.predict([[1,4,5,6,7,8,2,3,9,4,6]])

array([-35.19160106])